function setLegendInfo(this)
%SETLEGENDINFO Set legendinfo
%
%  SETLEGENDINFO(h)
%
 
%  Copyright 2008-2008 Fabian Kloosterman


lis.type = 'hggroup';
lisc(1).type = 'patch';
lisc(1).props = {...
    'LineWidth',this.LineWidth,...
    'EdgeColor',this.EdgeColor,...
    'FaceColor',this.FaceColor,...
    'LineStyle',this.LineStyle,...
    'XData',[0 0:12 12 0]/12, ...
    'YData',[0 0.1 0.25 0.45 0.55 0.5 0.4 0.4 0.6 0.8 0.85 0.7 0.5 0.35 0 0],...
    'FaceAlpha', this.Alpha};
lisc(2).type = 'line';
lisc(2).props = {...
    'LineStyle','none',...
    'Marker',this.Marker,...
    'MarkerEdgeColor',this.MarkerEdgeColor,...
    'MarkerFaceColor',this.MarkerFaceColor,...
    'MarkerSize',this.MarkerSize,...
    'XData',[3 9]/12,...
    'YData',[.55 0.85]};
lis.children = lisc;
legendinfo(this,lis);

% $$$ legendinfo(this,'patch',...
% $$$            'LineWidth',this.LineWidth,...
% $$$            'EdgeColor',this.EdgeColor,...
% $$$            'FaceColor',this.FaceColor,...
% $$$            'LineStyle',this.LineStyle,...
% $$$            'XData',[0 0:12 12 0]/12, ...
% $$$            'YData',[0 0.1 0.25 0.45 0.55 0.5 0.4 0.4 0.6 0.8 0.85 0.7 0.5 0.35 0 0],...
% $$$            'FaceAlpha', this.Alpha);

setappdata(double(this),'LegendLegendType','patch');