#! /bin/bash
#going to work in the data directory for now
working_dir=`pwd`
base=`basename $working_dir`
echo $base

spike_file_count=`ls | grep -c .tt`
echo $spike_file_count
if [[ $spike_file_count -gt 0 ]]
then
    echo inside if statement
    spike_file_list=*.tt
    echo "spike_file_list = $spike_file_list"
fi

for the_file in $spike_file_list
do
  echo "Processing file $the_file"
  filename=`basename $the_file`
  count=`echo $the_file | wc -c`

  if [ $count -gt 7 ]
      then
      probe0=`echo $filename | cut -c1-4`
  else
      probe0=`echo $filename | cut -c1-3`

   fi
  echo "Making directory: $probe0"
  mkdir $probe0
  mv $the_file $probe0/.
  spikeparms2 $probe0/$the_file -tetrode -binary -parms t_px,t_py,t_pa,t_pb,t_maxwd,t_maxht,time -pos *.p -o $probe0/$probe0.pxyabw
  echo "finished parming $the_file"
done
