function state = default_state( grid )

state = struct( 'x', 1, 'y', 2, 'z', 0, ...
                'slice_index', ones(1,ndims(grid)), ...
                'slice_index2', ones(1,ndims(grid))+1, ...
                'slice_index3', ones(1,ndims(grid))+1, ...
                'slice_method', {repmat({'slice'}, 1, ndims(grid))} );

