function f = define_exp_tt_anatomy(edir)
% A simple GUI to define sources (electrodes) and signals (data collected
% from those electrodes). 
% Written 2009 by Stuart Layton
f = figure('Position', [800 480 281 500], 'Name', 'Define Tetrode Anatomy', 'NumberTitle', 'off');


tetrodes =load_exp_tt_list(edir);

locations = repmat({'na'}, size(tetrodes));

data = [tetrodes, locations];
col_names = {'Tetrode', 'Location'};

u = uitable(f, 'Data', data, 'ColumnName', col_names, 'Units', 'Normalized',...
    'Position', [.05 .1 .9 .9], 'ColumnEditable', logical([0,1]));
set(u, 'Units', 'Pixels', 'ColumnWidth', {110, 110});
set(u, 'Units', 'Normalized');


load_def_btn = uicontrol('style', 'pushbutton', 'String', 'Load Default', 'Units', 'Normalized',...
    'Position', [.01 .015 .37 .05], 'CallBack', @load_defaults);

load_btn = uicontrol('style', 'pushbutton', 'string', 'Load', 'Units', 'Normalized',...
    'Position', [.4  .015 .18 .05], 'CallBack', @load_fn);

save_btn = uicontrol('style', 'pushbutton', 'String', 'Save', 'Units', 'Normalized',...
    'Position', [.6 .015 .18 .05], 'CallBack', @save_fn);

quit_btn = uicontrol('style', 'pushbutton', 'String', 'Quit', 'Units', 'Normalized',...
    'Position', [.8 .015 .18 .05], 'CallBack', @quit_fn);


saved = 0;

    function load_fn(varargin)
       if exist(fullfile(edir, 'tetrode_anatomy.mat'))
           dataIn = load(fullfile(edir, 'tetrode_anatomy.mat'));
           set(u, 'Data', dataIn.tt_anatomy);
       else
           errordlg('File does not exist');
       end    
    end

    function save_fn(varargin)
        answer = 'Yes';
        if exist(fullfile(edir, 'tetrode_anatomy.mat'))
            answer = questdlg('File exist, overwrite?');
        end

        if strcmp('Yes', answer)
            disp(['Saving: ',fullfile(edir, 'tetrode_anatomy.mat')]);
            tt_anatomy = get(u, 'Data');
            save(fullfile(edir,'tetrode_anatomy.mat'), 'tt_anatomy');
            saved = 1;    
        end
    end

    function quit_fn(varargin)
        if ~saved
            answer = questdlg('Would you like to save first?');
            if strcmp('Yes', answer)
                save_fn();
            elseif strcmp('Cancel', answer)
                    return
            end
        end
        close(f);
    end
    function load_defaults(varargin)
        prompt = 'Select Experiment Type';
        va = {  'CA1 - Right', ...
                'CA1 - Left', ...
                'CA1 - Bilateral', ...
                'CA3 - Right', ...
                'CA1 - Left', ...
                'CA3 - Bilateral', ...
                'other'
                };
        sel = listdlg('PromptString', prompt, 'liststring', va, 'SelectionMode', 'single');
        if isempty(sel)
            return
        end
        sel = va{sel};
        d = get(u, 'data');
        
        switch sel
            case 'CA1 - Right'
                d(:,2) = {'rCA1'};
            case 'CA1 - Left'
                d(:,2) = {'lCA1'};
            case 'CA3 - Right'
                d(:,2) = {'rCA3'};
            case 'CA3 - Left'
                d(:,2) = {'lCA3'};
            case 'CA1 - Bilateral'
                [yn ind] = ismember(d(:,1),bi_ca1_def);
                d(:,2) = bi_ca1_def(ind,2);
            case 'CA3 - Bilateral'
                [yn ind] = ismember(d(:,1),bi_ca3_def);
                d(:,2) = bi_ca3_def(ind,2);
        end
        set(u,'Data', d);
    end

    bi_ca1_def={'t01', 'rCA1'; ...
                't02', 'rCA1'; ...
                't03', 'rCA1'; ...
                't04', 'rCA1'; ...
                't05', 'rCA1'; ...
                't06', 'rCA1'; ...
                't07', 'rCA1'; ...
                't08', 'rCA1'; ...
                't09', 'rCA1'; ...
                't10', 'rCA1'; ...
                't11', 'rCA1'; ...
                't12', 'rCA1'; ...
                't13', 'lCA1'; ...
                't14', 'lCA1'; ...
                't15', 'lCA1'; ...
                't16', 'lCA1'; ...
                't17', 'lCA1'; ...
                't18', 'lCA1'; ...
                't19', 'lCA1'; ...
                't20', 'lCA1'; ...
                't21', 'lCA1'; ...
                't22', 'lCA1'; ...
                't23', 'lCA1'; ...
                't24', 'lCA1'; ...
                }; 



    bi_ca3_def={'t01', 'rCA3'; ...
                't02', 'rCA3'; ...
                't03', 'rCA3'; ...
                't04', 'rCA3'; ...
                't05', 'rCA3'; ...
                't06', 'rCA3'; ...
                't07', 'rCA3'; ...
                't08', 'rCA3'; ...
                't09', 'rCA3'; ...
                't10', 'rCA3'; ...
                't11', 'rCA3'; ...
                't12', 'rCA3'; ...
                't13', 'lCA3'; ...
                't14', 'lCA3'; ...
                't15', 'lCA3'; ...
                't16', 'lCA3'; ...
                't17', 'lCA3'; ...
                't18', 'lCA3'; ...
                't19', 'lCA3'; ...
                't20', 'lCA3'; ...
                't21', 'lCA3'; ...
                't22', 'lCA3'; ...
                't23', 'lCA3'; ...
                't24', 'lCA3'; ...
                };
end










