function mua_list = jk_mua_filelist()

base_path = '/home/greghale/exactamundo/031009';
day = '10';
%base_path = '/home/greghale/JK/092708';
%base_path = '/home/greghale/JK/092508';

mua_list.file_list = {[base_path, '/a1',day,'/a1',day,'.pxyabw'],...
    [base_path, '/a2',day,'/a2',day,'.pxyabw'],...
    [base_path, '/b1',day,'/b1',day,'.pxyabw'],...
    [base_path, '/b2',day,'/b2',day,'.pxyabw'],...
    [base_path, '/c1',day,'/c1',day,'.pxyabw'],...
    [base_path, '/c2',day,'/c2',day,'.pxyabw'],...
    [base_path, '/h1',day,'/h1',day,'.pxyabw'],...
    [base_path, '/h2',day,'/h2',day,'.pxyabw'],...
    };

mua_list.comp_list = {'a1','a2','b1','b2','c1','c2','h1','h2'};