function mua_list = hauser_mua_filelist(comp_list)

base_path = '/home/greghale/hauser/020409';
day = '04';
%base_path = '/home/greghale/JK/092708';
%base_path = '/home/greghale/JK/092508';

mua_list.file_list = {...
    [base_path, '/a1',day,'/a1',day,'.pxyabw'],...
    [base_path, '/a2',day,'/a2',day,'.pxyabw'],...
    [base_path, '/b1',day,'/b1',day,'.pxyabw'],...
    [base_path, '/b2',day,'/b2',day,'.pxyabw'],...
    [base_path, '/c1',day,'/c1',day,'.pxyabw'],...
    [base_path, '/c2',day,'/c2',day,'.pxyabw'],...
    [base_path, '/d1',day,'/d1',day,'.pxyabw'],...
    [base_path, '/d2',day,'/d2',day,'.pxyabw'],...
    [base_path, '/e1',day,'/e1',day,'.pxyabw'],...
    [base_path, '/e2',day,'/e2',day,'.pxyabw'],...
    [base_path, '/f1',day,'/f1',day,'.pxyabw'],...
    [base_path, '/f2',day,'/f2',day,'.pxyabw'],...
    [base_path, '/g1',day,'/g1',day,'.pxyabw'],...
    [base_path, '/g2',day,'/g2',day,'.pxyabw'],...
    [base_path, '/h1',day,'/h1',day,'.pxyabw'],...
    [base_path, '/h2',day,'/h2',day,'.pxyabw'],...
    [base_path, '/i1',day,'/i1',day,'.pxyabw'],...
    [base_path, '/i2',day,'/i2',day,'.pxyabw'],...
    };

mua_list.comp_list = {'a1','a2','b1','b2','c1','c2','d1','d2','e1','e2','f1','f2','g1','g2','h1','h2','i1','i2'};

if(not(isempty(comp_list)))
keep_comp = ones(1,18);
    for i = 1:18
        keep_comp(i) = sum(strcmp(mua_list.comp_list{i},comp_list));
    end
    keep_comp

    mua_list.file_list = mua_list.file_list(logical(keep_comp));
    mua_list.comp_list = mua_list.comp_list(logical(keep_comp));
end