function setLegendInfo(this)
%SETLEGENDINFO Set legendinfo
%
%  SETLEGENDINFO(h)
%
 
%  Copyright 2008-2008 Fabian Kloosterman

legendinfo(this,'patch',...
           'LineWidth',this.LineWidth,...
           'EdgeColor',this.EdgeColor,...
           'FaceColor',this.FaceColor,...
           'LineStyle',this.LineStyle,...
           'XData',[0 0 1 1 2 2 3 3 0]/3, ...
           'YData',[0 2 2 3 3 1 1 0 0]/3,...
           'FaceAlpha', this.Alpha);
 
setappdata(double(this),'LegendLegendType','patch');